name: CD

env:
  BLUE_EMAIL_HOST: "smtp-relay.sendinblue.com"
  BLUE_EMAIL_HOST_USER: "dummy"
  BLUE_EMAIL_HOST_PASSWORD: "dummy"

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install psycopg2
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run migrations
        run: |
          cd backend
          python3 manage.py migrate
      - name: Test with pytest
        run: |
          cd backend
          python3 manage.py test

  deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy in EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          host: ${{ secrets.HOST_NAME  }}
          username: ${{ secrets.USER_NAME  }}
          script: |
            cd codewithtemi
            ./deploy_script.sh
